# Generated by Django 3.0.5 on 2020-04-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0002_auto_20200426_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeruser',
            name='profile_image_ref',
            field=models.CharField(default='', max_length=50),
        ),
    ]
