# Generated by Django 3.0.5 on 2020-04-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0004_clientuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientUser',
        ),
    ]
