# Generated by Django 3.0.5 on 2020-04-29 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0005_auto_20200429_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livegrocerypost',
            name='client_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vogro_api.ClientUser'),
        ),
    ]
