# Generated by Django 3.0.5 on 2020-04-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0006_auto_20200429_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livegrocerypost',
            name='earliest_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='livegrocerypost',
            name='latest_time',
            field=models.DateTimeField(),
        ),
    ]
