# Generated by Django 3.0.5 on 2020-04-29 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0006_clientuser'),
        ('vogro_api', '0007_auto_20200429_0040'),
    ]

    operations = [
    ]
