# Generated by Django 3.0.5 on 2020-04-29 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0008_merge_20200429_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveGroceryPost',
        ),
    ]
