# Generated by Django 3.0.5 on 2020-05-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0012_merge_20200501_0231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaints',
        ),
    ]
