# Generated by Django 3.0.5 on 2020-05-01 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0014_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerGroceryPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_store_address', models.TextField()),
                ('grocery_store_address_name', models.CharField(max_length=50)),
                ('grocery_store_name', models.CharField(max_length=30)),
                ('time_of_grocery_shopping', models.DateTimeField()),
                ('earliest_time', models.DateTimeField()),
                ('latest_time', models.DateTimeField()),
                ('time_of_post', models.DateTimeField()),
                ('volunteer_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vogro_api.VolunteerUser')),
            ],
        ),
    ]
