# Generated by Django 3.0.5 on 2020-05-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vogro_api', '0015_volunteergrocerypost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolunteerGroceryPost',
        ),
    ]
